# Generated by Django 5.2.17 on 2026-08-27 08:42

import cameras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direction', models.CharField(blank=True, choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('NORTHEAST', 'Northeast'), ('NORTHWEST', 'Northwest'), ('SOUTHEAST', 'Southeast'), ('SOUTHWEST', 'Southwest')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OFFLINE', 'Offline')], default='INACTIVE', max_length=10)),
                ('api_key', models.CharField(default=cameras.models.generate_api_key, editable=False, max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['camera_code'],
            },
        ),
    ]
