# Generated by Django 5.2.17 on 2026-08-27 08:42

import detections.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('ocr_confidence', models.FloatField()),
                ('plate_image', models.ImageField(blank=True, null=True, upload_to=detections.models.plate_image_upload_path)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to=detections.models.vehicle_image_upload_path)),
                ('processing_source', models.CharField(choices=[('EDGE', 'Edge Node OCR'), ('SERVER_VERIFIED', 'Server-Verified OCR')], default='EDGE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='detections__vehicle_a5bc4c_idx'), models.Index(fields=['camera', 'timestamp'], name='detections__camera__7e4750_idx')],
            },
        ),
    ]
